version: '3.8'

services:
  vue-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile-vue
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - flask-app

  flask-app:
    build:
      context: ./api
      dockerfile: Dockerfile-flask
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
    - ./api:/api
